<?xml version="1.0" encoding="UTF-8" ?>
<!-- ENCOMPASS THESAURUS 2020 -->
<!DOCTYPE THESAURUS [
<!ELEMENT THESAURUS (CONCEPT+)>
<!ELEMENT CONCEPT ( (DESCRIPTOR|NON-DESCRIPTOR),TYPE*,YEAR*,INF*,SRH*,CAS*,CBT*,CA*,BT*,NT*,SA*,SEE*,UF*,USE*)>
<!ELEMENT DESCRIPTOR (#PCDATA)>
<!ELEMENT NON-DESCRIPTOR (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)>
<!ELEMENT YEAR (#PCDATA)>
<!ELEMENT INF (#PCDATA)>
<!ELEMENT SRH (#PCDATA)>
<!ELEMENT CAS (#PCDATA)>
<!ELEMENT CBT (#PCDATA)>
<!ELEMENT CA (#PCDATA)>
<!ELEMENT BT (#PCDATA)>
<!ELEMENT NT (#PCDATA)>
<!ELEMENT SA (#PCDATA)>
<!ELEMENT SEE (#PCDATA)>
<!ELEMENT LABEL ( #PCDATA ) >
<!ELEMENT PLUS ( LABEL+ ) >
<!ELEMENT STRING ( #PCDATA ) >
<!ELEMENT UF ( LABEL, PLUS? ) >
<!ELEMENT USE ( LABEL | PLUS | STRING )* >
]>

<THESAURUS>
<CONCEPT>
 <DESCRIPTOR>ABSORPTION</DESCRIPTOR>
<TYPE>TRM Index Term</TYPE>
 <INF>Phenomenon. Includes the absorption of a gas into a liquid; and also includes the absorption of electromagnetic radiation. For absorption (separation process) use ABSORPTION PROCESS. For absorption (optical density) use OPTICAL DENSITY.</INF>
 <BT>SORPTION</BT>
 <SA>ABSORBENT</SA>
 <SA>ABSORBER</SA>
 <SA>ABSORPTION PROCESS</SA>
 <SA>ABSORPTION SPECTROSCOPY</SA>
 <SA>ADSORPTION</SA>
 <SA>DESORPTION</SA>
 <SA>DIFFUSION</SA>
 <SA>HEAT OF ABSORPTION</SA>
 <SA>OPTICAL DENSITY</SA>
 <SA>PERMEABILITY</SA>
 <SA>UPTAKE</SA>
 <UF><LABEL>Absorptiveness</LABEL>
 </UF>
 <UF><LABEL>Imbibition</LABEL>
 </UF>
 <UF><LABEL>Radiation Absorption</LABEL><PLUS><LABEL>RADIATION</LABEL>
   </PLUS>
 </UF>
</CONCEPT>
</THESAURUS>