<?xml version="1.0" encoding="UTF-8" ?>
<!-- ENCOMPASS THESAURUS 2020 -->
<!DOCTYPE THESAURUS [
<!ELEMENT THESAURUS (CONCEPT+)>
<!ELEMENT CONCEPT ( (DESCRIPTOR|NON-DESCRIPTOR),TYPE*,YEAR*,INF*,SRH*,CAS*,CBT*,CA*,BT*,NT*,SA*,SEE*,UF*,USE*)>
<!ELEMENT DESCRIPTOR (#PCDATA)>
<!ELEMENT NON-DESCRIPTOR (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)>
<!ELEMENT YEAR (#PCDATA)>
<!ELEMENT INF (#PCDATA)>
<!ELEMENT SRH (#PCDATA)>
<!ELEMENT CAS (#PCDATA)>
<!ELEMENT CBT (#PCDATA)>
<!ELEMENT CA (#PCDATA)>
<!ELEMENT BT (#PCDATA)>
<!ELEMENT NT (#PCDATA)>
<!ELEMENT SA (#PCDATA)>
<!ELEMENT SEE (#PCDATA)>
<!ELEMENT LABEL ( #PCDATA ) >
<!ELEMENT PLUS ( LABEL+ ) >
<!ELEMENT STRING ( #PCDATA ) >
<!ELEMENT UF ( LABEL, PLUS? ) >
<!ELEMENT USE ( LABEL | PLUS | STRING )* >
]>

<THESAURUS>
<CONCEPT>
 <DESCRIPTOR>BATTERY</DESCRIPTOR>
<TYPE>TRM Index Term</TYPE>
 <BT>ELECTRIC POWER SOURCE</BT>
 <NT>FLOODED BATTERY</NT>
 <NT>FLOW BATTERY</NT> 
 <NT>GEL BATTERY</NT>
 <NT>LITHIUM ION BATTERY</NT>
 <NT>MOLTEN SALT BATTERY</NT>
 <SA>BATTERY CAPACITY</SA>
 <SA>BATTERY CHARGER</SA>
 <SA>BATTERY CHARGING RATE</SA>
 <SA>BATTERY DISCHARGE RATE</SA>
 <SA>BATTERY SEPARATOR</SA>
 <SA>CELL</SA>
 <SA>CHEMICAL ENERGY STORAGE</SA> 
 <SA>ELECTRODE</SA>
 <SA>ENERGY SOURCE</SA>
 <SA>HALF CELL</SA>
 <SA>HYDROGEN STORAGE</SA>
 <SA>IGNITION SYSTEM</SA>
 <SA>POWER INVERTER</SA>
 <SA>SELF-DISCHARGE</SA>
 <SA>SOLAR CELL</SA>
 <SA>SOLAR COLLECTOR</SA>
 <UF><LABEL>Solar Battery</LABEL><PLUS><LABEL>SOLAR ENERGY</LABEL>
   </PLUS>
 </UF>
 <UF><LABEL>Solar Cell</LABEL><PLUS><LABEL>SOLAR ENERGY</LABEL>
   </PLUS>
 </UF>
</CONCEPT>

</THESAURUS>