<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- REPORT GENERATOR -->
<!DOCTYPE THESAURUS [
<!ELEMENT THESAURUS (CONCEPT+)>
<!ELEMENT CONCEPT ( (DESCRIPTOR|NON-DESCRIPTOR),TT1*,SN*,UF*,USE*,BT*,RT*,NT*)>
<!ELEMENT DESCRIPTOR (#PCDATA)>
<!ELEMENT NON-DESCRIPTOR (#PCDATA)>
<!ELEMENT TT1 (#PCDATA)>
<!ELEMENT SN (#PCDATA)>
<!ELEMENT UF (#PCDATA)>
<!ELEMENT USE (#PCDATA)>
<!ELEMENT BT (#PCDATA)>
<!ELEMENT RT (#PCDATA)>
<!ELEMENT NT (#PCDATA)>
]>

<THESAURUS>
<CONCEPT>
 <DESCRIPTOR>1,3 dichloropropene</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>fumigant</BT>
 <BT>nematicide</BT>
 <BT>organochlorine pesticide</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>2,3,7,8 tetrachlorodibenzo para dioxin</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>TCDD</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>2,4 D</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>2,4 dichlorophenoxyacetic acid</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>2,4 dichlorophenoxyacetic acid</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>2,4 D</UF>
 <UF>2,4-D</UF>
 <UF>2,4-dichlorophenoxyacetic acid</UF>
 <BT>herbicide</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>2,4-D</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>2,4 dichlorophenoxyacetic acid</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>2,4-dichlorophenoxyacetic acid</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>2,4 dichlorophenoxyacetic acid</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>2019-nCoV Acute Respiratory Disease</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>COVID-19</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>2019-nCoV Disease</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>COVID-19</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>2019-nCoV Infection</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>COVID-19</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>A type rock</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>A-type rock</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>A-type rock</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>A type rock</UF>
 <BT>granite</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>aa lava</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>lava</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Aalenian</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>Jurassic</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abamectin</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>acaricide</BT>
 <BT>antibiotics</BT>
 <BT>insecticide</BT>
 <BT>nematicide</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abandoned land</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>land type</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abandoned mine</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>mine</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abatement cost</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>environmental tax</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Abee meteorite</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>enstatite chondrite</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abiotic factor</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>environmental factor</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>ablation</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>erosion</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abnormality</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>disease</BT>
 <RT>developmental biology</RT>
 <NT>cancer</NT>
 <NT>tumor</NT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>aboriginal people</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>indigenous population</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abortion</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>family planning</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>aboveground biomass</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>phytomass</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>aboveground production</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>biological production</BT>
 <RT>resource allocation</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abrasion</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>erosion</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abscisic acid</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>organic acid</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abscission</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>plant and fungus development</BT>
 <NT>litterfall</NT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>absolute gravimetry</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>gravimetry</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>absorbance</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>optical property</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>absorbing boundary</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <SN>use only in relation to porous media</SN>
 <BT>lithospheric and sublithospheric space</BT>
 <BT>surface</BT>
 <RT>wave propagation</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>absorption</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>sorption</BT>
 <RT>nutrient uptake</RT>
 <NT>absorption coefficient</NT>
 <NT>absorption spectrum</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>absorption coefficient</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>absorption</BT>
 <BT>dimensionless number</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>absorption efficiency</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <SN>use only in relation to organism feeding</SN>
 <BT>chemical property</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>absorption spectroscopy</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>atomic absorption spectroscopy</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>absorption spectrum</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>absorption</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abundance</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>population characteristics</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abundance estimation</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <SN>refers only to natural populations; for fishery stocks, use stock assessment</SN>
 <BT>biological method</BT>
 <BT>estimation method</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abundance index</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>biological indices and equations</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abyssal circulation</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>oceanic circulation</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>abyssal environment</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>abyssal zone</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abyssal hill</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <SN>topographic feature</SN>
 <BT>submarine feature</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abyssal organism</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>aquatic organism by aquatic zone</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abyssal plain</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>submarine feature</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abyssal zone</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <SN>benthic zone between about 2000m and 6000m depth</SN>
 <UF>abyssal environment</UF>
 <BT>hydrospheric space</BT>
 <BT>marine environment</BT>
 <BT>zone</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>academic performance</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>education and training</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>academic research</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>research by type</BT>
 <RT>higher education</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Acadian</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>Cambrian</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Acadian orogeny</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>Devonian</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acapulcoite</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>stony meteorite</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acaricide</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <SN>type of pesticide</SN>
 <BT>pesticide by target organism</BT>
 <NT>abamectin</NT>
 <NT>azinphos methyl</NT>
 <NT>bifenthrin</NT>
 <NT>carbaryl</NT>
 <NT>carbofuran</NT>
 <NT>chlorpyrifos</NT>
 <NT>cyhalothrin</NT>
 <NT>cypermethrin</NT>
 <NT>DDT</NT>
 <NT>diazinon</NT>
 <NT>dichlorvos</NT>
 <NT>endosulfan</NT>
 <NT>fenvalerate</NT>
 <NT>fipronil</NT>
 <NT>ivermectin</NT>
 <NT>malathion</NT>
 <NT>monocrotophos</NT>
 <NT>permethrin</NT>
 <NT>triazophos</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acceleration</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>force</BT>
 <NT>peak acceleration</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accelerator mass spectrometry</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>AMS</UF>
 <BT>mass spectrometry</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accelerometer</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>instrumentation</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>access restriction</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>legislation</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accessibility</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>Facet K: society and economy</BT>
 <RT>public access</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accessory mineral</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>mineral</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accident</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>accident, hazard, risk and related phenomena</BT>
 <RT>wreck</RT>
 <NT>collision</NT>
 <NT>explosion</NT>
 <NT>grounding (vessel)</NT>
 <NT>nuclear accident</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accident prevention</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>hazard management</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accident, hazard, risk and related phenomena</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>Facet I: environmental phenomena</BT>
 <NT>accident</NT>
 <NT>damage</NT>
 <NT>disaster</NT>
 <NT>hazard</NT>
 <NT>risk</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acclimation</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>acclimatization</UF>
 <BT>physiological processes and regulation</BT>
 <RT>adaptation</RT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>acclimatization</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>acclimation</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accountability</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>government and state</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accretion</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>crustal accretion</UF>
 <BT>sedimentological phenomena</BT>
 <NT>progradation</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accretionary prism</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>accretionary wedge</UF>
 <BT>tectonic structure</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>accretionary wedge</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>accretionary prism</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acculturation</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>cultural assimilation</UF>
 <BT>culture</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accumulation</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>general earth phenomena</BT>
 <NT>accumulation rate</NT>
 <NT>geoaccumulation</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accumulation rate</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>accumulation</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accuracy assessment</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <SN>use in reference to analytical methods or image processing</SN>
 <BT>accuracy, error and quality control procedure</BT>
 <BT>assessment method</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accuracy, error and quality control procedure</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>methodology</BT>
 <NT>accuracy assessment</NT>
 <NT>correction</NT>
 <NT>efficiency measurement</NT>
 <NT>error analysis</NT>
 <NT>model validation</NT>
 <NT>precision</NT>
 <NT>quality control</NT>
 <NT>reliability analysis</NT>
 <NT>sampling bias</NT>
 <NT>sensitivity analysis</NT>
 <NT>standardization</NT>
 <NT>uncertainty analysis</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>ACE 1</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>research program</BT>
 <RT>aerosol</RT>
 <RT>aerosol property</RT>
 <RT>atmospheric chemistry</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>ACE 2</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>research program</BT>
 <RT>aerosol</RT>
 <RT>aerosol property</RT>
 <RT>atmospheric chemistry</RT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Aceh-Andaman earthquake 2004</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>Sumatra earthquake 2004</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acetaldehyde</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>aldehyde</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acetate</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>carbonyl compound</BT>
 <NT>acetate (ester)</NT>
 <NT>acetate (salt)</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acetate (ester)</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>acetate</BT>
 <BT>ester</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acetate (salt)</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>acetate</BT>
 <BT>organic salt</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acetic acid</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>carboxylic acid</BT>
 <NT>DTPA</NT>
 <NT>EDTA</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acetochlor</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>herbicide</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acetone</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>ketone</BT>
 <BT>solvent</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acetylene</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>aliphatic hydrocarbon</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Acfer meteorite</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>meteorite</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>achene</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>fruit</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Acheulean</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>Acheulian</UF>
 <BT>Paleolithic</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Acheulian</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>Acheulean</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>achondrite</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>stony meteorite</BT>
 <NT>chladnite</NT>
 <NT>diogenite</NT>
 <NT>eucrite</NT>
 <NT>lunar meteorite</NT>
 <NT>Martian meteorite</NT>
 <NT>ureilite</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acid</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>chemical substance by activity or property</BT>
 <NT>inorganic acid</NT>
 <NT>organic acid</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acid activation</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>chemical method</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acid deposition</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>pollution by type</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acid digestion</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>chemical method</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acid mine drainage</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>mine drainage</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acid neutralization</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>chemical process</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acid precipitation</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>pollutant</BT>
 <BT>precipitation (climatology)</BT>
 <NT>acid rain</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acid rain</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>acid precipitation</BT>
 <BT>acid water</BT>
 <BT>rainwater</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acid soil</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>soil by form or property</BT>
 <BT>soil property</BT>
 <RT>heathland</RT>
 <NT>acid sulfate soil</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acid sulfate soil</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>acid sulphate soil</UF>
 <BT>acid soil</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>acid sulphate soil</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>acid sulfate soil</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acid water</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>water</BT>
 <NT>acid rain</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acidification</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>chemical process</BT>
 <NT>ocean acidification</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acidity</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>chemical property</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acidophily</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>habitat selection</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>acorn</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>seed</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acoustic array</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>acoustic equipment</BT>
 <BT>array</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>acoustic backscatter</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>backscatter</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acoustic data</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>acoustic phenomena</BT>
 <BT>data</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Acoustic Doppler Current Profiler</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>ADCP</UF>
 <BT>acoustic equipment</BT>
 <BT>oceanographic equipment</BT>
 <RT>current</RT>
 <RT>Doppler effect</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acoustic emission</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>acoustic phenomena</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acoustic equipment</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>equipment</BT>
 <NT>acoustic array</NT>
 <NT>Acoustic Doppler Current Profiler</NT>
 <NT>air gun</NT>
 <NT>echo sounder</NT>
 <NT>hydrophone</NT>
 <NT>sonar</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acoustic imagery</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>acoustic imaging</UF>
 <BT>acoustic method</BT>
 <BT>imagery</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>acoustic imaging</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>acoustic imagery</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acoustic logging</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>acoustic method</BT>
 <BT>logging (geophysics)</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acoustic method</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>acoustic technique</UF>
 <BT>physical method</BT>
 <NT>acoustic imagery</NT>
 <NT>acoustic logging</NT>
 <NT>acoustic tomography</NT>
 <NT>echo sounding</NT>
 <NT>echolocation</NT>
 <NT>target strength</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acoustic phenomena</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>physical phenomena</BT>
 <NT>acoustic data</NT>
 <NT>acoustic emission</NT>
 <NT>acoustic property</NT>
 <NT>acoustic wave</NT>
 <NT>noise</NT>
 <NT>sound propagation</NT>
 <NT>sound scattering</NT>
 <NT>sound velocity</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acoustic property</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>acoustic phenomena</BT>
 <BT>physical property</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acoustic survey</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>geophysical survey</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>acoustic technique</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>acoustic method</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acoustic tomography</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>acoustic method</BT>
 <BT>tomography</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acoustic wave</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>acoustic phenomena</BT>
 <BT>wave</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acoustics</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>physics</BT>
 <NT>bioacoustics</NT>
 <NT>infrasonics</NT>
 <NT>ultrasonics</NT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>ACP country</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>African-Caribbean-Pacific country</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acquired immune deficiency syndrome</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>AIDS</UF>
 <BT>viral disease</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Acrisol</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <SN>soil unit from highest category in FAO classification</SN>
 <BT>soil classification</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acritarch</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>microfossil</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acrotelm</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <SN>surface layer of a mire</SN>
 <BT>mire</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>actinic flux</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>ultraviolet radiation</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>actinide</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <SN>heavy radioactive metallic elements</SN>
 <BT>transition element</BT>
 <NT>americium</NT>
 <NT>neptunium</NT>
 <NT>plutonium</NT>
 <NT>protactinium</NT>
 <NT>thorium</NT>
 <NT>uranium</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>actinorhiza</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>actinorhizal plant</UF>
 <BT>symbiosis</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>actinorhizal plant</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>actinorhiza</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>action plan</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>planning process</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>action research</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>research by type</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>activated carbon</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>carbon</BT>
 <RT>adsorption</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>activated sludge</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>sludge</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>activation energy</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>chemical property</BT>
 <BT>energy</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>active control</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>earthquake engineering</BT>
 <RT>control system</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>active fault</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>fault</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>active layer</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <SN>top layer of ground above permafrost</SN>
 <BT>layer</BT>
 <RT>permafrost</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>active margin</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>tectonic feature</BT>
 <RT>plate boundary</RT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>activity budget</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>activity pattern</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>activity coefficient</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>dimensionless number</BT>
 <BT>thermodynamic property</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>activity pattern</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>activity budget</UF>
 <BT>behavior by movement, activity or response to stimuli</BT>
 <RT>biological rhythm</RT>
 <NT>circadian rhythm</NT>
 <NT>flight activity</NT>
 <NT>roosting</NT>
 <NT>sleep</NT>
 <NT>time allocation</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>actor network theory</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>social theory</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>acute respiratory infection</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>respiratory disease</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>acute toxicity</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>toxicity</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adakite</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>volcanic rock</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adaptation</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>evolution</BT>
 <RT>acclimation</RT>
 <RT>ecophysiology</RT>
 <RT>environmental stress</RT>
 <RT>estivation</RT>
 <RT>generalist</RT>
 <RT>mutation</RT>
 <RT>reaction norm</RT>
 <RT>specialist</RT>
 <RT>tolerance</RT>
 <NT>adaptive radiation</NT>
 <NT>bet-hedging</NT>
 <NT>convergent evolution</NT>
 <NT>divergence</NT>
 <NT>fitness</NT>
 <NT>local adaptation</NT>
 <NT>physical conditioning</NT>
 <NT>resource allocation</NT>
 <NT>specialization</NT>
 <NT>trade-off</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adaptive management</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>management</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adaptive radiation</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>adaptation</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>adaptive value</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>fitness</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>ADCP</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>Acoustic Doppler Current Profiler</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>additive</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>chemical substance by use or effect</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>ADEOS</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>Advanced Earth Observing Satellite</UF>
 <BT>satellite</BT>
 <RT>AVNIR</RT>
 <RT>NSCAT</RT>
 <RT>OCTS</RT>
 <RT>POLDER</RT>
 <RT>TOMS</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adhesion</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>general physical phenomena</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adiabatic lapse rate</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>atmospheric lapse rate</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adiabatic process</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>thermal phenomena</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adjoint method</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>numerical method</BT>
 <RT>data processing</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adjustment mechanism</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>adjustment policy</UF>
 <BT>economic policy</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>adjustment policy</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>adjustment mechanism</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>administration</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>government and state</BT>
 <NT>administrative framework</NT>
 <NT>administrative system</NT>
 <NT>public administration</NT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>administrative boundary</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>political boundary</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>administrative framework</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>administrative structure</UF>
 <BT>administration</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>administrative reform</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>reform process</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>administrative structure</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>administrative framework</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>administrative system</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>administration</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adolescence</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>biological development</BT>
 <RT>age</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adolescent sexuality</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>sexuality</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adoption behavior</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>adoption behaviour</UF>
 <BT>social behavior</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>adoption behaviour</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>adoption behavior</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adoption constraint</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>legislation</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adsorption</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>sorption</BT>
 <RT>activated carbon</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adularia</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>alkali feldspar</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adult</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>age structure</BT>
 <BT>developmental stage</BT>
 <BT>human group or individual</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adult education</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>education by type</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>advance rate</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>excavation</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Advanced Earth Observing Satellite</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>ADEOS</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Advanced Land Observation Satellite</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>ALOS</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Advanced Microwave Scanning Radiometer for EOS</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>AMSR-E</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Advanced Microwave Sounding Unit</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>AMSU</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Advanced SCATterometer</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>ASCAT</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Advanced Solid State Array Spectroradiometer</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>Advanced Solid-State Array Spectroradiometer</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Advanced Solid-State Array Spectroradiometer</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>Advanced Solid State Array Spectroradiometer</UF>
 <UF>ASAS</UF>
 <BT>airborne sensor</BT>
 <BT>radiometer</BT>
 <BT>scanner</BT>
 <RT>spectrometry</RT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Advanced Spaceborne Thermal Emission and Reflection Radiometer</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>ASTER</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>advanced technology</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>technology</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Advanced Traveler Information System</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <BT>information system</BT>
 <RT>planning method</RT>
 <RT>transportation planning</RT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Advanced Very High Resolution Radiometer</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>AVHRR</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Advanced Visible and Near Infrared Radiometer</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>AVNIR</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>advection</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>advective transport</UF>
 <BT>transport process</BT>
 <NT>advection-diffusion equation</NT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>advection diffusion equation</NON-DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <USE>advection-diffusion equation</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>advection-diffusion equation</DESCRIPTOR>
 <TT1>GDE Geobase</TT1>
 <UF>advection diffusion equation</UF>
 <BT>advection</BT>
 <BT>equation</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>advective transport</NON-DESCRIPTOR>